services:
  postgres:
    image: postgres:16-alpine

    container_name: servisbot-coding-challenge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: servisbot-coding-challenge
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U postgres -d servisbot-coding-challenge']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
